"use client";
import { useState } from "react";
import { schedulePost, uploadVideo, type Channel, type Video } from "@/lib/api";

export function UploadPanel({ channels, onUploaded }: { channels: Channel[]; onUploaded: (video: Video) => void }) {
  const [channelId, setChannelId] = useState(channels[0]?.id ?? "");
  const [file, setFile] = useState<File>();
  const [video, setVideo] = useState<Video>();
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [caption, setCaption] = useState(""); const [hashtags, setHashtags] = useState(""); const [isShort, setIsShort] = useState(false);
  const [when, setWhen] = useState("");
  const [message, setMessage] = useState("");
  async function upload() { if (!file || !channelId) return; setMessage("Uploading…"); try { const created = await uploadVideo(channelId, file); setVideo(created); setTitle(created.title); onUploaded(created); setMessage("Uploaded. Add metadata and schedule when ready."); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed"); } }
  async function schedule() { if (!video || !when) return; const channel = channels.find((item) => item.id === channelId); if (!channel) return; const metadata = channel.platform === "youtube" ? { title, description, tags: [], is_short: isShort } : { caption, hashtags: hashtags.split(/\s+/).filter(Boolean) }; setMessage("Saving…"); try { await schedulePost({ video_id: video.id, channel_id: channelId, scheduled_at: new Date(when).toISOString(), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, status: "scheduled", metadata }); setMessage("Scheduled locally. No platform publishing will occur."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not schedule"); } }
  const platform = channels.find((item) => item.id === channelId)?.platform;
  return <section className="card"><h2>Prepare content</h2><div className="form-grid"><label>Local target<select value={channelId} onChange={(event) => setChannelId(event.target.value)}>{channels.map((channel) => <option key={channel.id} value={channel.id}>{channel.name} · {channel.platform}</option>)}</select></label><label>Video file<input type="file" accept="video/mp4,video/quicktime,video/webm,video/x-msvideo" onChange={(event) => setFile(event.target.files?.[0])} /></label></div><button type="button" onClick={upload} disabled={!file || !channelId}>Upload video</button>{video && <><div className="form-grid">{platform === "youtube" ? <><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={100} /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} maxLength={5000} /></label><label className="check"><input type="checkbox" checked={isShort} onChange={(event) => setIsShort(event.target.checked)} /> YouTube Short</label></> : <><label>Caption<textarea value={caption} onChange={(event) => setCaption(event.target.value)} maxLength={2200} /></label><label>Hashtags<input value={hashtags} onChange={(event) => setHashtags(event.target.value)} placeholder="#creator #newvideo" /></label></>}<label>Posting time<input type="datetime-local" value={when} onChange={(event) => setWhen(event.target.value)} /></label></div><button type="button" onClick={schedule} disabled={!when || (platform === "youtube" ? !title : !caption)}>Save to queue</button></>}{message && <p role="status">{message}</p>}</section>;
}